FROM node:20-slim
RUN apt-get update && apt-get install -y \
    chromium \
    fonts-ipafont-gothic fonts-wqy-zenhei fonts-thai-tlwg fonts-kacst fonts-freefont-ttf \
    procps \
    --no-install-recommends && rm -rf /var/lib/apt/lists/* 